CREATE TABLE IF NOT EXISTS `groups` (
  `id` INT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(32) NOT NULL DEFAULT '',
  `keyword` VARCHAR(32) NOT NULL DEFAULT '',
  `level` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `time_edit` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `time_add` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `keyword` (`keyword`),
  KEY `level` (`level`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;